name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Run standard-version with input version
        id: release
        uses: ltv/standard-version-action@v1.8.0
        with:
         releaseAs: ${{ github.event.inputs.version }}

      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }} --follow-tags

      - name: Create main pull request
        id: create-main-pull-request
        uses: thomaseizinger/create-pull-request@1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: main
          labels: main
          title: "release/${{ github.event.inputs.version }}"
          reviewers: ${{ github.actor }} # By default, we request a review from the person who triggered the workflow.
          # Write a nice message to the user.
          # We are claiming things here based on the `publish-new-release.yml` workflow.
          # You should obviously adopt it to say the truth depending on your release workflow :)
          body: |
            ## Motivo da mudança

            Preencha o motivo da mudança.