name: "Publish new release"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    name: Publish new release
    env:
      GCP_PROJECT_ID: si26ef9dii9zscrxrecql6kl8eguw2
    runs-on: ubuntu-latest    
    if: github.event.pull_request.merged == true # only merged pull requests must trigger this job
    steps:
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix/}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract change reason from pull request body
        id: change-reason
        uses: actions/github-script@v7
        with:
          script: |
            const body = `${{ github.event.pull_request.body }}`;
            const match = body.match(/## Descrições das alterações([\s\S]*?)(?=<!-- auditing-block start -->)/);
            let text = match ? match[0] : '';
            // Format images as links
            text = text.replace(/!\[[^\]]*\]\((.*?)\)/g, '$1');
            core.setOutput('text', text);

      - name: Create Github Release
        id: create-github-release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          body: |
            ${{ steps.change-reason.outputs.text }}

      - name: 'Create PR: Merge main into develop branch'
        id: create-develop-pull-request
        uses: thomaseizinger/create-pull-request@1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: main
          base: develop
          labels: develop
          title: Merge main into develop branch
          body: |
            This PR merges the main branch back into develop.
            This happens to ensure that the updates that happend on the release branch, i.e. CHANGELOG and manifest updates are also present on the develop branch.
