name: Standard Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: false

jobs:

  create-release:
    runs-on: ubuntu-latest
    name: Standard Version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: Wuerike/standard-version-release-branch@feat/Create-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_version: ${{ github.event.inputs.version }}
          origin_branch: develop
          target_branch: master
          as_draft: 'true'