name: Standard Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: false

jobs:

  create-release:
    runs-on: ubuntu-latest
    name: Standard Version
    steps:
      - uses: Wuerike/standard-version-release-branch@main
        with:
          who-to-greet: 'Mona the Octocat'