name: Standard Version Flow Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: false

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Standard Version Flow Release
    steps:
      - uses: actions/checkout@v2

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Bumb version
        uses: Wuerike/standard-version-flow-release@master
        with:
          owner: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_as: ${{ github.event.inputs.version }}
          target_branch: master
          pull_request_body: 123